import Head from 'next/head'
import BasicLayout from '@/components/BasicLayout'
import Banner from '@/components/Banner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Suspense</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <Banner />

        <div className=" max-w-3xl mx-auto grid grid-rows-1 grid-cols-3">
          <div className="col-span-2">
            <p>상품 목록</p>
          </div>

          <div className="col-span-1">
            <p>유저 정보 및 알림</p>
          </div>
        </div>
      </BasicLayout>
    </>
  )
}
