import Head from 'next/head'
import BasicLayout from '@/components/BasicLayout'
import Banner from '@/components/Banner'
import Products from '@/components/Products'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Suspense</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <Banner />

        <div className=" max-w-3xl mx-auto grid grid-rows-1 grid-cols-3 gap-10">
          <div className="col-span-2">
            <h1 className="text-2xl font-bold text-center mt-8">
              추천 상품 목록
            </h1>

            <Products />

            <div className="btn-group w-100 flex justify-center mb-8">
              <button className="btn btn-active">1</button>
              <button className="btn">2</button>
              <button className="btn">3</button>
              <button className="btn">4</button>
            </div>
          </div>

          <div className="col-span-1 grid grid-rows-2 grid-cols-1 gap-5">
            <div>
              <h1 className="text-2xl font-bold text-center mt-8">유저 정보</h1>
            </div>
            <div>
              <h1 className="text-2xl font-bold text-center mt-8">알림</h1>
            </div>
          </div>
        </div>
      </BasicLayout>
    </>
  )
}
