import Head from 'next/head'
import BasicLayout from '@/components/BasicLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Suspense</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
        <section>메인 컨텐츠</section>
      </BasicLayout>
    </>
  )
}
